name = "lexia-function-suscriptions-v2"
main = "./src/index.ts"
compatibility_date = "2024-12-25"
compatibility_flags = ["nodejs_compat"]

account_id = "d821d06a70476db11364cd3d1ebb7d24"

[vars]
GATEWAY_SECRET = "BoAV0sZOcg6uyAX1LglyQY3wo9mIOVEI0mTs9w5r2PClZmFoGi"
OPENMETER_TOKEN = "om_hy8XwZ7gZQOAXM9DbUIRZhxdUFjKaF01.IX2r-UvhELv3MqTn6bCKEc7n64I0qkBCAzT36NaF4wk"

AWS_REGION = "us-east-1"
S3_BUCKET_NAME = "vault-lexia-dev"

[observability]
enabled = false

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "cd60532fec124dbebddcf623a8adc5b9"
localConnectionString = "postgresql://lexia_user:lexia_password@localhost:5432/lexia-saas"
